// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWb8xB9aHswlPfjAt4BBeREh5WyrZJ_m4',
    appId: '1:1091431715641:web:7ceebe07fbabc939344ee8',
    messagingSenderId: '1091431715641',
    projectId: 'quiz-app-ios-21ea9',
    authDomain: 'quiz-app-ios-21ea9.firebaseapp.com',
    storageBucket: 'quiz-app-ios-21ea9.appspot.com',
    measurementId: 'G-2ECZ4DJEDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjr4LIDaY4i9YhIMA5DCssAGA8NNtR9mU',
    appId: '1:1091431715641:android:5352fa6e5a66d6a0344ee8',
    messagingSenderId: '1091431715641',
    projectId: 'quiz-app-ios-21ea9',
    storageBucket: 'quiz-app-ios-21ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXU2zCvC08kY13zxeWSKtseo4p2hc_bg',
    appId: '1:1091431715641:ios:6a5f50539247f5fa344ee8',
    messagingSenderId: '1091431715641',
    projectId: 'quiz-app-ios-21ea9',
    storageBucket: 'quiz-app-ios-21ea9.appspot.com',
    iosClientId: '1091431715641-i0u07dpi1lu9mjibg88sb9ik229p3m9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp20230113',
  );
}
